---
- name: "Configure apps | using univention-app"
  univention.ucs_modules.univention_app:
    name: "{{ app_name }}"
    state: present
    auth_username: "Administrator"
    auth_password: "{{ root_password }}"
    config: "{{ app_vars }}"
  when: app_vars|dict2items|length > 0
- name: "Configure apps | using config registry"
  univention.ucs_modules.univention_config_registry:
    keys: "{{ ucr_vars }}"
  when: ucr_vars|dict2items|length > 0
- name: "Configure apps | restart services"
  ansible.builtin.service:
    name: "{{ srv }}"
    state: restarted
  loop: "{{ services }}"
  loop_control:
    loop_var: srv
  when: services|length > 0
