ansible_connection: "ssh"
ansible_ssh_user: "root"
ansible_ssh_pass: "univention"

upgrade_version: "5.0-5"
update_server: "updates.software-univention.de"

# Vars are replaced by default, so keep them in a 'global' dict here.
# Whenever a task needs global *and* per-host config, it can include both
# vars files and *MUST* merge the needed variables.
global:
  # will be installed before host-specific apps
  install_apps:
    - 'prometheus-node-exporter'
  # will be overridden by school_parameters in primary.yaml
  school_parameters:
    setup: 'multiserver'
    createDemo: false
    username: 'Administrator'
    # Next two: needed when doing join scripts on non-master roles?
    password: ''
    master: ''
    OUdisplayname: 'Pilot-Schule'
    schoolOU: 'pilotschule'
    server_type: 'educational'
    nameEduServer: ''
  # For app configuration, we expect this structure. Currently no need to use
  # this here; it would apply to all hosts where the given app is installed.
#  configure_apps:
#    appname:
#      app_config:
#        "configname": "config value"
#        "otherconfig":  "other value"
#      ucr_config:
#        "appname/some/var": "some value"
#        "appname/other/var": "other value"
#      restart:
#        - "service1"
#        - "service2"
