---
# Apps for backup
force_package_upgrade: "false"
install_apps:
  - "letsencrypt"
  - "keycloak"
  - "prometheus"
  - "self-service"
server_role: 'backup'

# FIXME: parameters for keycloak
configure_apps:
  # We refrain from setting apache2/{cert,chain,key} because with the unreliable behaviour
  # of acme_tiny.py (regards the 503 overload result) we risk having no webserver at all,
  # and this will effectively prevent further success (when trying to repeat the refresh)
  #
  # NOTE the requirement (allow this task to fail) is automatically fulfilled because
  #  neither `univention-app configure` nor `ucr` return exit codes on error :-(
  letsencrypt:
    app_config:
      "letsencrypt/domains": "insert.the.domain.here"
      "letsencrypt/services/apache2":  "True"
  "self-service":
    ucr_config:
      "umc/self-service/enabled": "yes"
      "umc/self-service/profiledata/enabled": "true"
      "umc/self-service/passwordchange/frontend/enabled": "true"
      "umc/self-service/passwordreset/frontend/enabled": "false"
      "umc/self-service/passwordreset/backend/enabled": "false"
      "umc/self-service/protect-account/frontend/enabled": "false"
      "umc/self-service/protect-account/backend/enabled": "false"

