---
# Apps for primary
force_package_upgrade: "false"
# this is only for 'additional apps': @school is being handled already.
install_apps:
  - "self-service-backend"
school_parameters:
  OUdisplayname: 'Name der Schule'
  schoolOU: 'schulname'

configure_apps:
  'self-service-backend':
    ucr_config:
      'self-service/udm_attributes': 'jpegPhoto,e-mail,roomNumber,departmentNumber,country,homeTelephoneNumber,mobileTelephoneNumber,homePostalAddress'
      'self-service/ldap_attributes': 'jpegPhoto,mail,roomNumber,departmentNumber,st,homePhone,mobile,homePostalAddress'
