---
# Apps for primary
force_package_upgrade: "false"
# this is only for 'additional apps': @school is being handled already.
install_apps:
  - "self-service-backend"
school_parameters:
  OUdisplayname: 'Name der Schule'
  schoolOU: 'schulname'
